### ISSUE TITLE
performance: somehow use single MutationObserver?

### ISSUE THREAD

**Issue by JakubKoralewski** [notion-enhancer/desktop#425]
**problem**

Notion becomes a bit slower than usual after enabling enhancer

**solution**

i saw quite many mods using their own MutationObserver on document.readystatechange === 'complete', why not merge it into one and callback into each, i.e. make a helper function?

**cons**

i really have no idea if this is possible, i don't understand how all this fits together tbh

**alternatives**

1. actually make a small framework, such that the mod creators could declaratively define what behavior they want to hook into, so that the helper/framework could make optimizations for this

2. OG Notion team should make an official addon store etc.

**Comment by dragonwocky** [comment]
most of the MutationObservers are observing different elements on the page. a helper function to create them wouldn't help, since you'd still need to create separate observers.

**Comment by JakubKoralewski** [comment]
I count 9 `observe(document.body` and 3 `observe(notion_elem`

**Comment by dragonwocky** [comment]
even when the whole document is being observed, actions are usually taken at different changes. also, since client javascript is single-threaded, there is a possibility that putting everything in one listening will actually end up being more blocking/laggy.

i'll do some experimentation, though. something at least similar probably would help (that's why i left this open).
