### ISSUE TITLE
Cards greyed out in gallery view + checkboxes won't change colour

### ISSUE THREAD

**Issue by jvvns** [notion-enhancer/desktop#561]
I installed Notion Enhancer today and I found it awesome except for a few visual things that seemed off. I use the **light theme** and the **gallery view cards had a grey background** to them instead of being white as they usually are, and **to-do boxes won't change colour** (except if you highlight text and select from there, but it won't change the colour of the checkbox).

I have no visual themes applied, so I don't think it is supposed to look like that. I have since uninstalled the enhancer, because one of the main reasons I wanted it was its visual enhancements, but those two little things made my pages look weird. I would like to know if there's any chance to get that fixed, or if any of the enhancements available are conflicting with the colours and are causing the issue!

I'm using **MacOS Big Sur 11.5**

Thanks a lot for your awesome help to the Notion community!

**Comment by dragonwocky** [comment]
This is a known bug - Notion has changed some things since the enhancer was released, and so the theming overrides don't apply perfectly (even if no theme is currently installed the overrides are active). A new theming system is work-in-progress, but I haven't had a lot of time to work on it so it's not ready to use yet.

**Comment by jvvns** [comment]
Ah, thank you so much and sorry for bringing it up then!

Have a nice day
