### ISSUE TITLE
Narrower table columns

### ISSUE THREAD

**Issue by vnavone** [notion-enhancer/desktop#651]
**problem**

Columns in Notion's databases are often too wide for small values.  I believe they have a minimum of 100 pixels wide, so if a column only contains a 1-2 digit number, this results in a lot of wasted space.

**solution**

how will this feature appear/act?

We can already drag the width of columns wider and smaller; I would like to see the minimum width reduced so we can drag them even narrower.  Perhaps there could be an option to "shrink column to data width".

**cons**

I don't see any downsides.  Column titles might get truncated, but this is already possible with longer property titles.

**alternatives**

I don't see any.

**Comment by dragonwocky** [comment]
it can be done manually per-column by adding css custom insert, but there isn't a way to be able to drag them below the 100px limit

https://github.com/notion-enhancer/tweaks/blob/main/tweaks/table%20columns%20below%20100px.md

**Comment by MarkGStacey** [comment]
Why was this closed if the feature was never implemented?

**Comment by dragonwocky** [comment]
@MarkGStacey because... it's never going to be implemented, other than in the way that I linked, so there were no more actions to take related to this issue. If an issue is no longer relevant (out of scope, implemented, invalid, etc.) it gets closed so that I know that the ones that are opened do need attention. That's what opening/closing an issue is for: to determine what has been dealt with and what still needs attention.

**Comment by MarkGStacey** [comment]
Very sad that it will never be implemented.

The mobile view is crippled, you can only see 2 columns when 10 or so would fit

**Comment by vnavone** [comment]
You can already do this with a simple hack. Change the property type to a checklist, resize, then change it back to the correct property type. You won’t lose anything. It’s a hassle, but it’s worked for a year or two.

**Comment by dragonwocky** [comment]
> Very sad that it will never be implemented.

There are multiple ways to do it! Either you can use some custom styling to make the column narrower, or use the workaround @vnavone described above. It's not impossible to have narrower columns, the way you do it just isn't as a toggleable option.

Possibly in future I'll revisit the feature and find a way to do it as a simple switch, but for now, there are already other options.

> The mobile view is crippled, you can only see 2 columns when 10 or so would fit

The notion-enhancer doesn't support mobile devices anyway? So I'm not sure how this feature would help you if your issue is with the mobile view.
