### ISSUE TITLE
LAGS

### ISSUE THREAD

**Issue by TvoozMagnificent** [notion-enhancer/desktop#734]
Seriously. L. A. G. S. 

This thing lags, crazily. 
1. can't scroll
2. can't type
3. pics take years to show

Tried google-chrome-add-on and app-mac-os but both failed. 
Runs like shit. 
I am from china, but I have no Chinese characters inside the thing. 
This lags for only one of my files. 
Tried with and without a VPN. Fails. 
Exact content inside my file is [here](https://paste.me/paste/fc5e52eb-4d42-486b-7709-8f52451cca4e#fb5a93ca32ea53e634542e1ceda392c37b55ca24d94a9bcfbedebfff42854e9b) Direct CopyPaste

THANKS!!!

**Comment by TvoozMagnificent** [comment]
Sorry, exact content moved to here: https://paste.me/paste/28828f7a-2638-4e25-40c0-0e3f200f6ad4#2df9e95d6388d649018ee9df58b7426673f5f4482e4d1cc4cc605e251d22b6b5

**Comment by dragonwocky** [comment]
if you can figure out a consistent way to reproduce the lag, open an issue about the cause of the lag in https://github.com/notion-enhancer/repo/issues

otherwise, I can't reproduce this and you have neither followed the provided issue template, the contributing guide (<https://notion-enhancer.github.io/about/contributing/>) or the code of conduct (<https://notion-enhancer.github.io/about/code-of-conduct/>). a degree of lag is unavoidable (see <https://notion-enhancer.github.io/documentation/concepts/>), but lag shouldn't be completely blocking usage.
