### ISSUE TITLE
help

### ISSUE THREAD

**Issue by parsak1231** [notion-enhancer/desktop#804]
hello I am new to Github.
please help me with notion-enhancer
I couldn't find client.js and another else
please help me to find it

**Comment by dragonwocky** [comment]
@parsak1231 I'm not really sure what you're trying to do/find, because you don't need to edit any client.js files to use the notion-enhancer, but if you would like someone to help you get up and running with the notion-enhancer, the right place to ask is in the Discord server: https://discord.gg/sFWPXtA

GitHub is for reporting/documenting actual bugs and feature requests, not for user support. Thanks.
